Use autopilot to handle blue/green deploy of broker app.

diff --git a/jobs/deploy-service-broker/templates/deploy.sh.erb b/jobs/deploy-service-broker/templates/deploy.sh.erb
--- a/jobs/deploy-service-broker/templates/deploy.sh.erb
+++ b/jobs/deploy-service-broker/templates/deploy.sh.erb
@@ -1,6 +1,6 @@
-#!/bin/bash
-set -e -x
+#!/bin/bash -exu
 
+<%# TODO support variable instance count %>
   <%
     def grab_app_domain_name
       app_domains_str = properties.app_domains.to_s
@@ -20,14 +20,15 @@ SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 export PATH="/var/vcap/packages/cf_cli/bin:$PATH"
 
 export SCHEME=https
+<%# TODO use credhub for password storage/retreival %>
 export ADMIN_USER=<%= properties.cf.admin_user %>
 export ADMIN_PASSWORD=<%= properties.cf.admin_password %>
 export DOMAIN=<%= properties.domain %>
 export APP_DOMAIN=<%="#{app_domain}"%>
 export API_ENDPOINT=$SCHEME://api.${DOMAIN}
 export APP_NAME=<%= properties.app_name %>
-export APP_VERSION=<%= properties.app_version %>
 export APP_URI=<%= properties.app_uri %>
+<%# TODO customize org/space/quota in properties from tile %>
 export ORG=${APP_NAME}-service-org
 export SPACE=${APP_NAME}-service-space
 export QUOTA=${APP_NAME}-service-quota
@@ -40,13 +41,12 @@ export CF_SKIP_SSL=<%= properties.ssl.skip_cert_verify %>
 export ORG_QUOTA=<%= properties.org_quota %>
 export APP_PUSH_TIMEOUT=<%= properties.timeout %>
 export APP_PUSH_MEMORY=<%= properties.memory %>
-
+<%# TODO use credhub for password storage/retreival %>
 export SECURITY_USERNAME=<%= properties.security_username %>
 export SECURITY_PASSWORD=<%= properties.security_password %>
 export BROKER_CERTIFICATE="<%= properties.certificate %>"
 
 export CREATE_OPEN_SECURITY_GROUP=<%= properties.create_open_security_group %>
-export DELETE_PREV_APP_INSTANCE=<%= properties.delete_prev_app_instance %>
 
 export EXPLODED_APP_FOLDER="exploded-app-contents"
 
@@ -103,14 +103,14 @@ function create_open_security_group() {
 }
 
 function restart_app() {
-  CF_TRACE=true cf restart ${APP_NAME}-${APP_VERSION}
-  cf logs ${APP_NAME}-${APP_VERSION} --recent
+  CF_TRACE=true cf restart ${APP_NAME}
+  cf logs ${APP_NAME} --recent
 }
 
 function wait_till_running() {
   for i in `seq 1  6`
   do
-    CF_TRACE=true cf app ${APP_NAME}-${APP_VERSION} | grep RUNNING | grep ${APP_NAME}-${APP_VERSION}
+    CF_TRACE=true cf app ${APP_NAME} | grep RUNNING | grep ${APP_NAME}
     if [ "$?" -ne "0" ]; then
       log_debug "App not running yet..."
       sleep 10
@@ -135,98 +135,92 @@ function modify_app() {
   popd
 }
 
-function delete_prev_app_instance() {
-
-  cf apps | grep ${APP_NAME}-${APP_VERSION}
-  existing_app_check=$?
-
-  if [ "$existing_app_check" == "0" ]; then
-
-    # Look for User-Provided env variables and stop after the first blank line after that
-    cf env ${APP_NAME}-${APP_VERSION} | awk 'f{print}/User-Provided/{f=1};/^ *$/{f=0}' \
-                | grep '.' | awk -F ':' '{print $1}' | while read env_variable_name
-    do
-      cf unset-env $env_variable_name
-    done
-    cf delete -f ${APP_NAME}-${APP_VERSION}  > /dev/null
-  fi
-}
-
 function push_app() {
+  local exit_code
+
+  mkdir -p /var/vcap/data/tmp
+  export TMPDIR=/var/vcap/data/tmp
+
+  pushd ${PACKAGE_PATH} > /dev/null
+    set +e
+      cf app $APP_NAME --guid
+      exit_code=$?
+    set -e
+
+    if [[ $exit_code -ne 0 ]]; then
+      set +e
+        cf push -i 1
+        exit_code=$?
+      set -e
+
+      if [[ $exit_code -ne 0 ]]; then
+        cf logs "${APP_NAME}" --recent
+        exit "${exit_code}"
+      fi
+
+    else
+      cf install-plugin /var/vcap/packages/cf_cli/plugins/autopilot -f
+      set +e
+        cf zero-downtime-push "${APP_NAME}" -f manifest.yml -p "${PWD}"
+        exit_code=$?
+      set -e
+      if [[ $exit_code -ne 0 ]]; then
+        handle_failed_blue_green_deploy
+      fi
+    fi
+  popd > /dev/null
+
+  <%#
   pushd $PACKAGE_PATH
     mkdir -p /var/vcap/data/tmp
     export TMPDIR=/var/vcap/data/tmp
 
     # TODO -- add back in the timeouts and quotas for the app push?  Or remove them from the errand props?
 
-    cf push ${APP_NAME}-${APP_VERSION} -p ${PACKAGE_PATH}/lib/${TARGET_APP}  -n ${APP_URI} -d ${APP_DOMAIN}  --no-start
-    cf logs ${APP_NAME}-${APP_VERSION} --recent
+    cf push ${APP_NAME} -p ${PACKAGE_PATH}/lib/${TARGET_APP}  -n ${APP_URI} -d ${APP_DOMAIN}  --no-start
+    cf logs ${APP_NAME} --recent
   popd
+  %>
 }
 
-function register_on_demand_plans() {
-  pushd $PACKAGE_PATH
-    mkdir -p /var/vcap/data/tmp
-    # Sleep for a bit so the app is up
-    sleep 30
-    app_endpoint=http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@${APP_URI}.${APP_DOMAIN}
-    app_catalog_url=${app_endpoint}/v2/catalog
-    catalog_output=`curl -X GET ${app_catalog_url} 2>/dev/null`
-    log_debug "Service Broker App Catalog output : $catalog_output"
+function handle_failed_blue_green_deploy() {
+    DEPLOYMENT_STATUS=1
+    local notifications_state=$(cf curl /v2/apps/$(cf app $APP_NAME --guid)/stats | jq -r '.["0"].state')
+    local venerable_state=$(cf curl /v2/apps/$(cf app $APP_NAME-venerable --guid)/stats | jq -r '.["0"].state')
 
-    service_id=`echo $catalog_output | sed -e 's/"//g'  | sed -e "s/name:/\nname:/g" | grep "id:" | grep services | sed -e "s/^.*id://g;s/,//" `
-    #plan_id=`echo $catalog_output | sed -e 's/"//g'  | sed -e "s/name:/\nname:/g" | grep "id:" | grep plans | sed -e "s/^.*id://g;s/,//" `
-    log_debug "Catalog Service Id : $service_id "
+    # if venerable is up, and new app is down
+    if [[ $notifications_state = "DOWN" && $venerable_state != "DOWN" ]]; then
+      cf delete $APP_NAME -f
+      cf rename $APP_NAME-venerable $APP_NAME
+    fi
 
-    <% if properties.on_demand_service_plans %>
-      <%  p("on_demand_service_plans").each do |plan|
-             plan_name=plan['plan_name']
-             plan_descrp=plan['plan_description']
-             plan_details=plan['plan_details'].gsub('\n','')
-      %>
-        export PLAN_ID=<%="#{plan_name}"%>
-        export PLAN_DESCRP=<%="#{plan_descrp}"%>
-        export PLAN_DETAILS='<%="#{plan_details}"%>'
-        log_debug "Service plan name ${PLAN_ID}, described as ${PLAN_DESCRP} and details: ${PLAN_DETAILS}"
-
-        bullets_name_value_multiline=`echo $PLAN_DETAILS | sed -e "s/;/,/g" | awk -F ":" '{print "\"" $1 "\" : \"" $2 "\", " }' `
-        bullets_value_descrp_singleline=`echo $PLAN_DETAILS | sed -e "s/;/,\n/g;"  | awk -F ":" '{print "\""$2  $3"\"" }' | sed -e 's/,"/",/g' `
-
-        cat > /var/vcap/data/tmp/${PLAN_ID}.service_plan.json << EOF
-{
-  "name" : "$PLAN_ID",
-  "description" : "$PLAN_DESCRP",
-  "metadata" : {
-     "name" : "$PLAN_ID",
-     "displayName" : "$PLAN_ID",
-     "description" : "$PLAN_DESCRP",
-     $bullets_name_value_multiline
-     "bullets" : [
-        "$PLAN_ID $PLAN_DESCRP",
-        $bullets_value_descrp_singleline ]
-   }
+    # if venerable is up, and new app is up
+    if [[ $notifications_state != "DOWN" && $venerable_state != "DOWN" ]]; then
+      cf delete $APP_NAME-venerable -f
+    fi
 }
-EOF
 
-         log_debug "Copied over default service plan file template with ${PLAN_ID} and updated it"
-         new_plan=`cat /var/vcap/data/tmp/${PLAN_ID}.service_plan.json`
-         log_debug "Contents of the plan: ${new_plan} "
-         plan_creation_output=`curl ${app_catalog_url}/services/${service_id}/plans -X POST -H "Content-Type:application/json" -d @/var/vcap/data/tmp/${PLAN_ID}.service_plan.json `
-         log_debug "Service Plan created!!"
-         log_debug "Service Plan details: ${plan_creation_output}"
-       <% end %>
-    <% end %>
+function print_deployment_status() {
+  if [[ $DEPLOYMENT_STATUS != 0 ]]; then
+    echo "Deployment failed!"
+    exit 1
+  fi
 
-  popd
+  echo "Deployment succeeded!"
+}
+
+function cleanup_cf_home() {
+  if [[ -d "${CF_HOME}" ]]; then
+    rm -rf "${CF_HOME}"
+  fi
 }
 
 cf -v
 authenticate_and_target
 create_open_security_group
 create_quota
-
 modify_app
 push_app
-
-restart_app
 wait_till_running
+print_deployment_status
+cleanup_cf_home
